### ISSUE TITLE
HTMLでvariableが効かない

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-front#501]
```css
html {
  color: getColor(--color-text-main);
}
```
はダークモードで効かない。`.dark`以下じゃないとダークモードの変数にならないため。
なのでこの行をbodyに移す。
